# Generated by Django 2.0.4 on 2018-04-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x_axis', models.PositiveSmallIntegerField(default=1)),
                ('y_axis', models.PositiveSmallIntegerField(default=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missiles', related_query_name='missiles', to='boards.Board')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='missile',
            unique_together={('board', 'x_axis', 'y_axis')},
        ),
        migrations.AlterIndexTogether(
            name='missile',
            index_together={('board', 'x_axis', 'y_axis')},
        ),
    ]
