# Generated by Django 2.0.4 on 2018-04-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_type', models.CharField(choices=[('battleship', 'battleship'), ('cruiser', 'cruiser'), ('destroyer', 'destroyer'), ('submarine', 'submarine')], default='battleship', max_length=20)),
                ('x_axis', models.PositiveSmallIntegerField(default=1)),
                ('y_axis', models.PositiveSmallIntegerField(default=1)),
                ('occupied', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', related_query_name='fleets', to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='BattleShip',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('fleets.fleet',),
        ),
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together={('board', 'x_axis', 'y_axis')},
        ),
        migrations.AlterIndexTogether(
            name='fleet',
            index_together={('board', 'x_axis', 'y_axis')},
        ),
    ]
