# Generated by Django 2.0.4 on 2018-04-21 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_auto_20180421_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='ship_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
