# Generated by Django 2.0.4 on 2018-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0003_fleet_ship_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
